### ISSUE TITLE
runtime errors

### ISSUE THREAD

**Issue by rrodstein** [20c/vaping#31]
Hi, and thank you in advance for your support! 

I've installed vaping on ubuntu 17.04 following the instructions from https://github.com/20c/vaping, and the tip from "Run issue on Ubuntu 16.04 #22", i.e. pip install pluginmgr==0.4.0. after installing pluginmgr==0.4.0 we get the bellow error with any vaping command. 

$ vaping start
Traceback (most recent call last):
  File "/usr/local/bin/vaping", line 7, in <module>
    from vaping.cli import cli
  File "/usr/local/lib/python2.7/dist-packages/vaping/__init__.py", line 5, in <module>
    from pluginmgr.config import ConfigPluginManager
ImportError: No module named pluginmgr.config

$ cat ~/.vaping/config.yml 
vaping:
  pidfile: vaping.pid
  plugin_path: []

  probes: [] 
  plugins: []

Respectfully,

**Comment by vegu** [comment]
The issue in #22 should actually been fixed with the recent release we did, can you paste your output of running `pip freeze` please

In any case you can probably do either of these to fix:

A) Run vaping 0.4.0 and pluginmgr 0.4.0 - py3 support is broken in that release

```
pip install vaping==0.4.0
pip install pluginmgr==0.4.0
```

B) Run latest for both vaping and pluginmgr

```
pip install vaping -U
pip install pluginmgr -U
````
Would be interested to see if B) works for you, please let me know if it does so i can close #22 as well. Thanks.

**Comment by vegu** [comment]
I have the same version of gevent installed on my test setup, but this might shed some light on what you are seeing: https://github.com/gevent/gevent/issues/1052

**Comment by rrodstein** [comment]
Thank you again for your time and awesome project! vaping installed, and runs great on a fresh 16.04 vm. We are cooking with gas!

May I ask if you know who is primarily installing/using vaping, i.e. sys admins, network ops, developers, or app owners? 

I ask because over the years I've supported both commercial and open source latency visualization solutions, and I'm curious who these days is deploying vaping. 

Respectfully,
