### ISSUE TITLE
documentation request - Distributed DNS example 

### ISSUE THREAD

**Issue by matthewmdn** [20c/vaping#57]
I'm sure I just don't know what I'm doing here, but I'm looking for an example in the docs about how to run the distributed DNS example on multiple hosts. There's a section there about it, but it doesn't mention running or connecting to zeromq.

I was able to get it working after: pip install -U pyzmq

The main thing that's missing for me is how to run these on separate hosts. I'd like to build a central collector, also running the webserver for viewing, but have probes running from several small python capable devices at each important hop in my network. How do i run zmq at that collector and point all the probes to it, or am I thinking about this wrong?

Also, is it possible to swap out the mq with something like aws MQ. I was thinking about running this as a serverless app collecting data from different probes on my network.

**Comment by vegu** [comment]
So looking at https://github.com/20c/vaping/tree/master/examples/distributed_dns

There are two directories in there, one called `vodka` and one called `vaping`

`vodka` is the vaping config that runs the vodka web service (so this would be your web server)
`vaping` is the vaping config that would run vaping with fping (or other models) and send the data to `vodka`

Both are meant to be run in separate vaping processes and can be on separate hosts.

Going by the example to start the web server on one host (using gunicorn to run it):

```
export VODKA_HOME=examples/distributed_dns/vodka
gunicorn -b 0.0.0.0:7021 vodka.runners.wsgi:application
```

And then start the fping vaping on a different host:

```
vaping start --home=examples/distributed_dns/vaping/ --debug
```

You will want to also look at both configs and update the addresses in zeromq_probe (vodka) and zeromq (vaping) accordingly. Please be aware of https://github.com/20c/vodka/issues/11 since it's a bit counterintuitive atm.

Hope that clears it up a little, let me know if not.

> Also, is it possible to swap out the mq with something like aws MQ. I was thinking about running this as a serverless app collecting data from different probes on my network.

A plugin would need to be written for it for both vaping and vodka (if you want to view it in the web ui)

**Comment by vegu** [comment]
Made some edits to my comment above to further clarify, please also have a look at https://vaping.readthedocs.io/en/latest/examples/#two-distributed-vaping-instances-into-the-same-graph as that also involves the webserver and two different vaping hosts (albeit going into the same graph, but it should still clarify the set up a bit)

**Comment by matthewmdn** [comment]
This is very helpful. I think the key is "In the vodka config each zeromq connection is instantiated by the zeromq_probe plugin, so it needs one of those for each vaping sending data."
I was just getting a little hung up on how to separate it out and still point the vaping instances at one web server. So zmq is using a different port for each topic?

BTW, if there is a better place to discuss other than a github issue, I'm glad to move there (e.g https://www.networktocode.com/community/)

Also I'd be happy to add some documentation for another example once I work through this.
Thanks
